# Generated by Django 3.1.2 on 2020-10-20 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsSec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HowSec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TopsliderSec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('paragraph', models.TextField()),
                ('button_label', models.CharField(max_length=30)),
                ('background_image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='HowStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('icon_image', models.ImageField(upload_to='images')),
                ('how_sec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pageconfig.howsec')),
            ],
        ),
        migrations.CreateModel(
            name='Clienticon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(upload_to='images')),
                ('clients_sec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pageconfig.clientssec')),
            ],
        ),
    ]
