# Generated by Django 3.1.2 on 2020-10-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageconfig', '0002_contactinfo_informationcorner_partner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='contact',
            new_name='contact_by',
        ),
        migrations.AlterField(
            model_name='informationcorner',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='partner',
            name='link',
            field=models.CharField(max_length=100),
        ),
    ]
